version: '3.9'

services:

  # ================= USER SERVICE =================
  user-service:
    build: ./user-service
    env_file:
      - ./user-service/.env
    depends_on:
      - user-db
      - rabbitmq
    expose:
      - "8081"

  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db/users:/var/lib/postgresql/data

  # ================= ORDER SERVICE =================
  order-service:
    build: ./order-service
    env_file:
      - ./order-service/.env
    depends_on:
      - order-db
      - rabbitmq
    expose:
      - "8082"

  order-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ordersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db/orders:/var/lib/postgresql/data

  # ================= PRODUCT SERVICE =================
  product-service:
    build: ./product-service
    env_file:
      - ./product-service/.env
    depends_on:
      - product-db
      - rabbitmq
    expose:
      - "8083"

  product-db:
    image: postgres:15
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./db/products:/var/lib/postgresql/data

  # ================= RABBITMQ =================
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"   # UI doar pentru debug
    expose:
      - "5672"

  # ================= WEB SERVER (API GATEWAY) =================
  web-server-1:
    build: ./web-server
    env_file:
      - ./web-server/.env
    depends_on:
      - user-service
      - order-service
      - product-service
    expose:
      - "8085"

  web-server-2:
    build: ./web-server
    env_file:
      - ./web-server/.env
    depends_on:
      - user-service
      - order-service
      - product-service
    expose:
      - "8085"

  # ================= NGINX (LOAD BALANCER) =================
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web-server-1
      - web-server-2
