user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    # Define upstream-uri
    upstream user-service {
        server user-service:8081;
    }

    upstream product-service {
        server product-service:8083;
    }

    upstream order-service {
        server order-service:8082;
    }

    upstream web-server {
        server web-server:8085;
        server web-server2:8086;
    }

    server {
        listen 80;

        location /api/users {
            proxy_pass http://user-service/;
        }

        location /api/orders {
            proxy_pass http://order-service/;
        }

        location /api/products {
            proxy_pass http://product-service/;
        }

        # Web-server (Gateway)
        location /auth/ {
            proxy_pass http://web-server/;
        }
    }
}
