user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    # === Upstream-uri ===
    upstream user-service {
        server user-service:8081;
    }

    upstream product-service {
        server product-service:8083;
    }

    upstream order-service {
        server order-service:8082;
    }

    # 🔥 LOAD BALANCER pentru Web Server
    upstream web-server {
        server web-server-1:8085;
        server web-server-2:8085;
    }

    server {
        listen 80;

        # ===== API =====
        location /api/users/ {
            proxy_pass http://web-server;
        }

        location /api/orders/ {
            proxy_pass http://web-server;
        }

        location /api/products/ {
            proxy_pass http://web-server;
        }

        # ===== AUTH =====
        location /auth/ {
            proxy_pass http://web-server;
        }
    }
}
